Question a

In [26]:
import numpy as np

matrix = np.array([[1, -2, 3],
 [4, 5, 6],
 [7, 3, 9]])


In [27]:
linalg.det(matrix)

-54.0

Question b

In [3]:
vector = np.array([1, 2, 3])

Question c

In [28]:
from scipy import linalg
res = linalg.solve(matrix,vector)

Question d

In [5]:
np.dot(matrix,res)

array([1., 2., 3.])

Question e

In [29]:
matrixb = np.random.randint(0,5,(3,3))
print(matrixb)
resb = linalg.solve(matrix,matrixb)
np.dot(matrix,resb)

[[2 2 4]
 [1 2 1]
 [1 1 1]]


array([[2., 2., 4.],
       [1., 2., 1.],
       [1., 1., 1.]])

Question f

In [14]:
values, vector = linalg.eig(matrix)
print(values)
print(vector)

[ 1.61168440e+01+0.j -1.11684397e+00+0.j -4.22209278e-16+0.j]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


Question g

In [31]:
matrix_inv = linalg.inv(matrix)
print(matrix_inv)

[[-0.5        -0.5         0.5       ]
 [-0.11111111  0.22222222 -0.11111111]
 [ 0.42592593  0.31481481 -0.24074074]]


Question h

In [30]:
print(linalg.norm(matrix))
print(linalg.norm(matrix,2))
print(linalg.norm(matrix,-1))
print(linalg.norm(matrix,-2))

15.165750888103101
14.636945300837017
10.0
0.9576017627507012


STATISTICS

Question a

a. Create a discrete random variable with poissonian distribution and plot its probability mass function (PMF), cummulative distribution function (CDF) and a histogram of 1000 random realizations of the variable